### ISSUE TITLE
low level PMCs with high level plates in armor

### ISSUE THREAD

**Issue by scottiedawg66** [VforValens/Progression#9] opened 2024-04-07 03:04 UTC
**Describe the bug**
low level PMCs with level 5 and 6 plates in low level armor (Ie press armor with level 5, floral armor with level 6 plates 
**To Reproduce**
kill a some PMCs and inspect their armor 

**Smartphone (please complete the following information):**
 SPT 3.8.0

**Comment by VforValens** [comment] 2024-04-07 03:26
Known "issue" that is a to do at some point. No eta. However this is currently intended behavior as this is how base SPT handles armor plates, they are randomly generated like everything else.

**Comment by VforValens** [comment] 2024-04-08 03:21
Fixed with https://github.com/VforValens/Progression/commit/2f9de93ab02a86d0593c9e6daa96dd58fdf7c8e6

**Closed** 2024-04-08 03:22 UTC
Labels: enhancement
